spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: justwe77
    url: jdbc:mysql://172.17.0.10:3306/eat?characterEncoding=utf8&useSSL=false
    username: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
logging:
  level:
    com:
      yang:
        dao: debug
